<option value=""></option>
<option value="AF"<?php echo preselectOption('AF', $selectedCountryCode); ?>>Afghanistan</option>
<option value="AX"<?php echo preselectOption('AX', $selectedCountryCode); ?>>Åland Islands</option>
<option value="AL"<?php echo preselectOption('AL', $selectedCountryCode); ?>>Albania</option>
<option value="DZ"<?php echo preselectOption('DZ', $selectedCountryCode); ?>>Algeria</option>
<option value="AS"<?php echo preselectOption('AS', $selectedCountryCode); ?>>American Samoa</option>
<option value="AD"<?php echo preselectOption('AD', $selectedCountryCode); ?>>Andorra</option>
<option value="AO"<?php echo preselectOption('AO', $selectedCountryCode); ?>>Angola</option>
<option value="AI"<?php echo preselectOption('AI', $selectedCountryCode); ?>>Anguilla</option>
<option value="AQ"<?php echo preselectOption('AQ', $selectedCountryCode); ?>>Antarctica</option>
<option value="AG"<?php echo preselectOption('AG', $selectedCountryCode); ?>>Antigua and Barbuda</option>
<option value="AR"<?php echo preselectOption('AR', $selectedCountryCode); ?>>Argentina</option>
<option value="AM"<?php echo preselectOption('AM', $selectedCountryCode); ?>>Armenia</option>
<option value="AW"<?php echo preselectOption('AW', $selectedCountryCode); ?>>Aruba</option>
<option value="AU"<?php echo preselectOption('AU', $selectedCountryCode); ?>>Australia</option>
<option value="AT"<?php echo preselectOption('AT', $selectedCountryCode); ?>>Austria</option>
<option value="AZ"<?php echo preselectOption('AZ', $selectedCountryCode); ?>>Azerbaijan</option>
<option value="BS"<?php echo preselectOption('BS', $selectedCountryCode); ?>>Bahamas</option>
<option value="BH"<?php echo preselectOption('BH', $selectedCountryCode); ?>>Bahrain</option>
<option value="BD"<?php echo preselectOption('BD', $selectedCountryCode); ?>>Bangladesh</option>
<option value="BB"<?php echo preselectOption('BB', $selectedCountryCode); ?>>Barbados</option>
<option value="BY"<?php echo preselectOption('BY', $selectedCountryCode); ?>>Belarus</option>
<option value="BE"<?php echo preselectOption('BE', $selectedCountryCode); ?>>Belgium</option>
<option value="BZ"<?php echo preselectOption('BZ', $selectedCountryCode); ?>>Belize</option>
<option value="BJ"<?php echo preselectOption('BJ', $selectedCountryCode); ?>>Benin</option>
<option value="BM"<?php echo preselectOption('BM', $selectedCountryCode); ?>>Bermuda</option>
<option value="BT"<?php echo preselectOption('BT', $selectedCountryCode); ?>>Bhutan</option>
<option value="BO"<?php echo preselectOption('BO', $selectedCountryCode); ?>>Bolivia, Plurinational State of</option>
<option value="BQ"<?php echo preselectOption('BQ', $selectedCountryCode); ?>>Bonaire, Sint Eustatius and Saba</option>
<option value="BA"<?php echo preselectOption('BA', $selectedCountryCode); ?>>Bosnia and Herzegovina</option>
<option value="BW"<?php echo preselectOption('BW', $selectedCountryCode); ?>>Botswana</option>
<option value="BV"<?php echo preselectOption('BV', $selectedCountryCode); ?>>Bouvet Island</option>
<option value="BR"<?php echo preselectOption('BR', $selectedCountryCode); ?>>Brazil</option>
<option value="IO"<?php echo preselectOption('IO', $selectedCountryCode); ?>>British Indian Ocean Territory</option>
<option value="BN"<?php echo preselectOption('BN', $selectedCountryCode); ?>>Brunei Darussalam</option>
<option value="BG"<?php echo preselectOption('BG', $selectedCountryCode); ?>>Bulgaria</option>
<option value="BF"<?php echo preselectOption('BF', $selectedCountryCode); ?>>Burkina Faso</option>
<option value="BI"<?php echo preselectOption('BI', $selectedCountryCode); ?>>Burundi</option>
<option value="KH"<?php echo preselectOption('KH', $selectedCountryCode); ?>>Cambodia</option>
<option value="CM"<?php echo preselectOption('CM', $selectedCountryCode); ?>>Cameroon</option>
<option value="CA"<?php echo preselectOption('CA', $selectedCountryCode); ?>>Canada</option>
<option value="CV"<?php echo preselectOption('CV', $selectedCountryCode); ?>>Cape Verde</option>
<option value="KY"<?php echo preselectOption('KY', $selectedCountryCode); ?>>Cayman Islands</option>
<option value="CF"<?php echo preselectOption('CF', $selectedCountryCode); ?>>Central African Republic</option>
<option value="TD"<?php echo preselectOption('TD', $selectedCountryCode); ?>>Chad</option>
<option value="CL"<?php echo preselectOption('CL', $selectedCountryCode); ?>>Chile</option>
<option value="CN"<?php echo preselectOption('CN', $selectedCountryCode); ?>>China</option>
<option value="CX"<?php echo preselectOption('CX', $selectedCountryCode); ?>>Christmas Island</option>
<option value="CC"<?php echo preselectOption('CC', $selectedCountryCode); ?>>Cocos (Keeling) Islands</option>
<option value="CO"<?php echo preselectOption('CO', $selectedCountryCode); ?>>Colombia</option>
<option value="KM"<?php echo preselectOption('KM', $selectedCountryCode); ?>>Comoros</option>
<option value="CG"<?php echo preselectOption('CG', $selectedCountryCode); ?>>Congo</option>
<option value="CD"<?php echo preselectOption('CD', $selectedCountryCode); ?>>Congo, the Democratic Republic of the</option>
<option value="CK"<?php echo preselectOption('CK', $selectedCountryCode); ?>>Cook Islands</option>
<option value="CR"<?php echo preselectOption('CR', $selectedCountryCode); ?>>Costa Rica</option>
<option value="CI"<?php echo preselectOption('CI', $selectedCountryCode); ?>>Côte d'Ivoire</option>
<option value="HR"<?php echo preselectOption('HR', $selectedCountryCode); ?>>Croatia</option>
<option value="CU"<?php echo preselectOption('CU', $selectedCountryCode); ?>>Cuba</option>
<option value="CW"<?php echo preselectOption('CW', $selectedCountryCode); ?>>Curaçao</option>
<option value="CY"<?php echo preselectOption('CY', $selectedCountryCode); ?>>Cyprus</option>
<option value="CZ"<?php echo preselectOption('CZ', $selectedCountryCode); ?>>Czech Republic</option>
<option value="DK"<?php echo preselectOption('DK', $selectedCountryCode); ?>>Denmark</option>
<option value="DJ"<?php echo preselectOption('DJ', $selectedCountryCode); ?>>Djibouti</option>
<option value="DM"<?php echo preselectOption('DM', $selectedCountryCode); ?>>Dominica</option>
<option value="DO"<?php echo preselectOption('DO', $selectedCountryCode); ?>>Dominican Republic</option>
<option value="EC"<?php echo preselectOption('EC', $selectedCountryCode); ?>>Ecuador</option>
<option value="EG"<?php echo preselectOption('EG', $selectedCountryCode); ?>>Egypt</option>
<option value="SV"<?php echo preselectOption('SV', $selectedCountryCode); ?>>El Salvador</option>
<option value="GQ"<?php echo preselectOption('GQ', $selectedCountryCode); ?>>Equatorial Guinea</option>
<option value="ER"<?php echo preselectOption('ER', $selectedCountryCode); ?>>Eritrea</option>
<option value="EE"<?php echo preselectOption('EE', $selectedCountryCode); ?>>Estonia</option>
<option value="ET"<?php echo preselectOption('ET', $selectedCountryCode); ?>>Ethiopia</option>
<option value="FK"<?php echo preselectOption('FK', $selectedCountryCode); ?>>Falkland Islands (Malvinas)</option>
<option value="FO"<?php echo preselectOption('FO', $selectedCountryCode); ?>>Faroe Islands</option>
<option value="FJ"<?php echo preselectOption('FJ', $selectedCountryCode); ?>>Fiji</option>
<option value="FI"<?php echo preselectOption('FI', $selectedCountryCode); ?>>Finland</option>
<option value="FR"<?php echo preselectOption('FR', $selectedCountryCode); ?>>France</option>
<option value="GF"<?php echo preselectOption('GF', $selectedCountryCode); ?>>French Guiana</option>
<option value="PF"<?php echo preselectOption('PF', $selectedCountryCode); ?>>French Polynesia</option>
<option value="TF"<?php echo preselectOption('TF', $selectedCountryCode); ?>>French Southern Territories</option>
<option value="GA"<?php echo preselectOption('GA', $selectedCountryCode); ?>>Gabon</option>
<option value="GM"<?php echo preselectOption('GM', $selectedCountryCode); ?>>Gambia</option>
<option value="GE"<?php echo preselectOption('GE', $selectedCountryCode); ?>>Georgia</option>
<option value="DE"<?php echo preselectOption('DE', $selectedCountryCode); ?>>Germany</option>
<option value="GH"<?php echo preselectOption('GH', $selectedCountryCode); ?>>Ghana</option>
<option value="GI"<?php echo preselectOption('GI', $selectedCountryCode); ?>>Gibraltar</option>
<option value="GR"<?php echo preselectOption('GR', $selectedCountryCode); ?>>Greece</option>
<option value="GL"<?php echo preselectOption('GL', $selectedCountryCode); ?>>Greenland</option>
<option value="GD"<?php echo preselectOption('GD', $selectedCountryCode); ?>>Grenada</option>
<option value="GP"<?php echo preselectOption('GP', $selectedCountryCode); ?>>Guadeloupe</option>
<option value="GU"<?php echo preselectOption('GU', $selectedCountryCode); ?>>Guam</option>
<option value="GT"<?php echo preselectOption('GT', $selectedCountryCode); ?>>Guatemala</option>
<option value="GG"<?php echo preselectOption('GG', $selectedCountryCode); ?>>Guernsey</option>
<option value="GN"<?php echo preselectOption('GN', $selectedCountryCode); ?>>Guinea</option>
<option value="GW"<?php echo preselectOption('GW', $selectedCountryCode); ?>>Guinea-Bissau</option>
<option value="GY"<?php echo preselectOption('GY', $selectedCountryCode); ?>>Guyana</option>
<option value="HT"<?php echo preselectOption('HT', $selectedCountryCode); ?>>Haiti</option>
<option value="HM"<?php echo preselectOption('HM', $selectedCountryCode); ?>>Heard Island and McDonald Islands</option>
<option value="VA"<?php echo preselectOption('VA', $selectedCountryCode); ?>>Holy See (Vatican City State)</option>
<option value="HN"<?php echo preselectOption('HN', $selectedCountryCode); ?>>Honduras</option>
<option value="HK"<?php echo preselectOption('HK', $selectedCountryCode); ?>>Hong Kong</option>
<option value="HU"<?php echo preselectOption('HU', $selectedCountryCode); ?>>Hungary</option>
<option value="IS"<?php echo preselectOption('IS', $selectedCountryCode); ?>>Iceland</option>
<option value="IN"<?php echo preselectOption('IN', $selectedCountryCode); ?>>India</option>
<option value="ID"<?php echo preselectOption('ID', $selectedCountryCode); ?>>Indonesia</option>
<option value="IR"<?php echo preselectOption('IR', $selectedCountryCode); ?>>Iran, Islamic Republic of</option>
<option value="IQ"<?php echo preselectOption('IQ', $selectedCountryCode); ?>>Iraq</option>
<option value="IE"<?php echo preselectOption('IE', $selectedCountryCode); ?>>Ireland</option>
<option value="IM"<?php echo preselectOption('IM', $selectedCountryCode); ?>>Isle of Man</option>
<option value="IL"<?php echo preselectOption('IL', $selectedCountryCode); ?>>Israel</option>
<option value="IT"<?php echo preselectOption('IT', $selectedCountryCode); ?>>Italy</option>
<option value="JM"<?php echo preselectOption('JM', $selectedCountryCode); ?>>Jamaica</option>
<option value="JP"<?php echo preselectOption('JP', $selectedCountryCode); ?>>Japan</option>
<option value="JE"<?php echo preselectOption('JE', $selectedCountryCode); ?>>Jersey</option>
<option value="JO"<?php echo preselectOption('JO', $selectedCountryCode); ?>>Jordan</option>
<option value="KZ"<?php echo preselectOption('KZ', $selectedCountryCode); ?>>Kazakhstan</option>
<option value="KE"<?php echo preselectOption('KE', $selectedCountryCode); ?>>Kenya</option>
<option value="KI"<?php echo preselectOption('KI', $selectedCountryCode); ?>>Kiribati</option>
<option value="KP"<?php echo preselectOption('KP', $selectedCountryCode); ?>>Korea, Democratic People's Republic of</option>
<option value="KR"<?php echo preselectOption('KR', $selectedCountryCode); ?>>Korea, Republic of</option>
<option value="KW"<?php echo preselectOption('KW', $selectedCountryCode); ?>>Kuwait</option>
<option value="KG"<?php echo preselectOption('KG', $selectedCountryCode); ?>>Kyrgyzstan</option>
<option value="LA"<?php echo preselectOption('LA', $selectedCountryCode); ?>>Lao People's Democratic Republic</option>
<option value="LV"<?php echo preselectOption('LV', $selectedCountryCode); ?>>Latvia</option>
<option value="LB"<?php echo preselectOption('LB', $selectedCountryCode); ?>>Lebanon</option>
<option value="LS"<?php echo preselectOption('LS', $selectedCountryCode); ?>>Lesotho</option>
<option value="LR"<?php echo preselectOption('LR', $selectedCountryCode); ?>>Liberia</option>
<option value="LY"<?php echo preselectOption('LY', $selectedCountryCode); ?>>Libya</option>
<option value="LI"<?php echo preselectOption('LI', $selectedCountryCode); ?>>Liechtenstein</option>
<option value="LT"<?php echo preselectOption('LT', $selectedCountryCode); ?>>Lithuania</option>
<option value="LU"<?php echo preselectOption('LU', $selectedCountryCode); ?>>Luxembourg</option>
<option value="MO"<?php echo preselectOption('MO', $selectedCountryCode); ?>>Macao</option>
<option value="MK"<?php echo preselectOption('MK', $selectedCountryCode); ?>>Macedonia, the former Yugoslav Republic of</option>
<option value="MG"<?php echo preselectOption('MG', $selectedCountryCode); ?>>Madagascar</option>
<option value="MW"<?php echo preselectOption('MW', $selectedCountryCode); ?>>Malawi</option>
<option value="MY"<?php echo preselectOption('MY', $selectedCountryCode); ?>>Malaysia</option>
<option value="MV"<?php echo preselectOption('MV', $selectedCountryCode); ?>>Maldives</option>
<option value="ML"<?php echo preselectOption('ML', $selectedCountryCode); ?>>Mali</option>
<option value="MT"<?php echo preselectOption('MT', $selectedCountryCode); ?>>Malta</option>
<option value="MH"<?php echo preselectOption('MH', $selectedCountryCode); ?>>Marshall Islands</option>
<option value="MQ"<?php echo preselectOption('MQ', $selectedCountryCode); ?>>Martinique</option>
<option value="MR"<?php echo preselectOption('MR', $selectedCountryCode); ?>>Mauritania</option>
<option value="MU"<?php echo preselectOption('MU', $selectedCountryCode); ?>>Mauritius</option>
<option value="YT"<?php echo preselectOption('YT', $selectedCountryCode); ?>>Mayotte</option>
<option value="MX"<?php echo preselectOption('MX', $selectedCountryCode); ?>>Mexico</option>
<option value="FM"<?php echo preselectOption('FM', $selectedCountryCode); ?>>Micronesia, Federated States of</option>
<option value="MD"<?php echo preselectOption('MD', $selectedCountryCode); ?>>Moldova, Republic of</option>
<option value="MC"<?php echo preselectOption('MC', $selectedCountryCode); ?>>Monaco</option>
<option value="MN"<?php echo preselectOption('MN', $selectedCountryCode); ?>>Mongolia</option>
<option value="ME"<?php echo preselectOption('ME', $selectedCountryCode); ?>>Montenegro</option>
<option value="MS"<?php echo preselectOption('MS', $selectedCountryCode); ?>>Montserrat</option>
<option value="MA"<?php echo preselectOption('MA', $selectedCountryCode); ?>>Morocco</option>
<option value="MZ"<?php echo preselectOption('MZ', $selectedCountryCode); ?>>Mozambique</option>
<option value="MM"<?php echo preselectOption('MM', $selectedCountryCode); ?>>Myanmar</option>
<option value="NA"<?php echo preselectOption('NA', $selectedCountryCode); ?>>Namibia</option>
<option value="NR"<?php echo preselectOption('NR', $selectedCountryCode); ?>>Nauru</option>
<option value="NP"<?php echo preselectOption('NP', $selectedCountryCode); ?>>Nepal</option>
<option value="NL"<?php echo preselectOption('NL', $selectedCountryCode); ?>>Netherlands</option>
<option value="NC"<?php echo preselectOption('NC', $selectedCountryCode); ?>>New Caledonia</option>
<option value="NZ"<?php echo preselectOption('NZ', $selectedCountryCode); ?>>New Zealand</option>
<option value="NI"<?php echo preselectOption('NI', $selectedCountryCode); ?>>Nicaragua</option>
<option value="NE"<?php echo preselectOption('NE', $selectedCountryCode); ?>>Niger</option>
<option value="NG"<?php echo preselectOption('NG', $selectedCountryCode); ?>>Nigeria</option>
<option value="NU"<?php echo preselectOption('NU', $selectedCountryCode); ?>>Niue</option>
<option value="NF"<?php echo preselectOption('NF', $selectedCountryCode); ?>>Norfolk Island</option>
<option value="MP"<?php echo preselectOption('MP', $selectedCountryCode); ?>>Northern Mariana Islands</option>
<option value="NO"<?php echo preselectOption('NO', $selectedCountryCode); ?>>Norway</option>
<option value="OM"<?php echo preselectOption('OM', $selectedCountryCode); ?>>Oman</option>
<option value="PK"<?php echo preselectOption('PK', $selectedCountryCode); ?>>Pakistan</option>
<option value="PW"<?php echo preselectOption('PW', $selectedCountryCode); ?>>Palau</option>
<option value="PS"<?php echo preselectOption('PS', $selectedCountryCode); ?>>Palestinian Territory, Occupied</option>
<option value="PA"<?php echo preselectOption('PA', $selectedCountryCode); ?>>Panama</option>
<option value="PG"<?php echo preselectOption('PG', $selectedCountryCode); ?>>Papua New Guinea</option>
<option value="PY"<?php echo preselectOption('PY', $selectedCountryCode); ?>>Paraguay</option>
<option value="PE"<?php echo preselectOption('PE', $selectedCountryCode); ?>>Peru</option>
<option value="PH"<?php echo preselectOption('PH', $selectedCountryCode); ?>>Philippines</option>
<option value="PN"<?php echo preselectOption('PN', $selectedCountryCode); ?>>Pitcairn</option>
<option value="PL"<?php echo preselectOption('PL', $selectedCountryCode); ?>>Poland</option>
<option value="PT"<?php echo preselectOption('PT', $selectedCountryCode); ?>>Portugal</option>
<option value="PR"<?php echo preselectOption('PR', $selectedCountryCode); ?>>Puerto Rico</option>
<option value="QA"<?php echo preselectOption('QA', $selectedCountryCode); ?>>Qatar</option>
<option value="RE"<?php echo preselectOption('RE', $selectedCountryCode); ?>>Réunion</option>
<option value="RO"<?php echo preselectOption('RO', $selectedCountryCode); ?>>Romania</option>
<option value="RU"<?php echo preselectOption('RU', $selectedCountryCode); ?>>Russian Federation</option>
<option value="RW"<?php echo preselectOption('RW', $selectedCountryCode); ?>>Rwanda</option>
<option value="BL"<?php echo preselectOption('BL', $selectedCountryCode); ?>>Saint Barthélemy</option>
<option value="SH"<?php echo preselectOption('SH', $selectedCountryCode); ?>>Saint Helena, Ascension and Tristan da Cunha</option>
<option value="KN"<?php echo preselectOption('KN', $selectedCountryCode); ?>>Saint Kitts and Nevis</option>
<option value="LC"<?php echo preselectOption('LC', $selectedCountryCode); ?>>Saint Lucia</option>
<option value="MF"<?php echo preselectOption('MF', $selectedCountryCode); ?>>Saint Martin (French part)</option>
<option value="PM"<?php echo preselectOption('PM', $selectedCountryCode); ?>>Saint Pierre and Miquelon</option>
<option value="VC"<?php echo preselectOption('VC', $selectedCountryCode); ?>>Saint Vincent and the Grenadines</option>
<option value="WS"<?php echo preselectOption('WS', $selectedCountryCode); ?>>Samoa</option>
<option value="SM"<?php echo preselectOption('SM', $selectedCountryCode); ?>>San Marino</option>
<option value="ST"<?php echo preselectOption('ST', $selectedCountryCode); ?>>Sao Tome and Principe</option>
<option value="SA"<?php echo preselectOption('SA', $selectedCountryCode); ?>>Saudi Arabia</option>
<option value="SN"<?php echo preselectOption('SN', $selectedCountryCode); ?>>Senegal</option>
<option value="RS"<?php echo preselectOption('RS', $selectedCountryCode); ?>>Serbia</option>
<option value="SC"<?php echo preselectOption('SC', $selectedCountryCode); ?>>Seychelles</option>
<option value="SL"<?php echo preselectOption('SL', $selectedCountryCode); ?>>Sierra Leone</option>
<option value="SG"<?php echo preselectOption('SG', $selectedCountryCode); ?>>Singapore</option>
<option value="SX"<?php echo preselectOption('SX', $selectedCountryCode); ?>>Sint Maarten (Dutch part)</option>
<option value="SK"<?php echo preselectOption('SK', $selectedCountryCode); ?>>Slovakia</option>
<option value="SI"<?php echo preselectOption('SI', $selectedCountryCode); ?>>Slovenia</option>
<option value="SB"<?php echo preselectOption('SB', $selectedCountryCode); ?>>Solomon Islands</option>
<option value="SO"<?php echo preselectOption('SO', $selectedCountryCode); ?>>Somalia</option>
<option value="ZA"<?php echo preselectOption('ZA', $selectedCountryCode); ?>>South Africa</option>
<option value="GS"<?php echo preselectOption('GS', $selectedCountryCode); ?>>South Georgia and the South Sandwich Islands</option>
<option value="SS"<?php echo preselectOption('SS', $selectedCountryCode); ?>>South Sudan</option>
<option value="ES"<?php echo preselectOption('ES', $selectedCountryCode); ?>>Spain</option>
<option value="LK"<?php echo preselectOption('LK', $selectedCountryCode); ?>>Sri Lanka</option>
<option value="SD"<?php echo preselectOption('SD', $selectedCountryCode); ?>>Sudan</option>
<option value="SR"<?php echo preselectOption('SR', $selectedCountryCode); ?>>Suriname</option>
<option value="SJ"<?php echo preselectOption('SJ', $selectedCountryCode); ?>>Svalbard and Jan Mayen</option>
<option value="SZ"<?php echo preselectOption('SZ', $selectedCountryCode); ?>>Swaziland</option>
<option value="SE"<?php echo preselectOption('SE', $selectedCountryCode); ?>>Sweden</option>
<option value="CH"<?php echo preselectOption('CH', $selectedCountryCode); ?>>Switzerland</option>
<option value="SY"<?php echo preselectOption('SY', $selectedCountryCode); ?>>Syrian Arab Republic</option>
<option value="TW"<?php echo preselectOption('TW', $selectedCountryCode); ?>>Taiwan, Province of China</option>
<option value="TJ"<?php echo preselectOption('TJ', $selectedCountryCode); ?>>Tajikistan</option>
<option value="TZ"<?php echo preselectOption('TZ', $selectedCountryCode); ?>>Tanzania, United Republic of</option>
<option value="TH"<?php echo preselectOption('TH', $selectedCountryCode); ?>>Thailand</option>
<option value="TL"<?php echo preselectOption('TL', $selectedCountryCode); ?>>Timor-Leste</option>
<option value="TG"<?php echo preselectOption('TG', $selectedCountryCode); ?>>Togo</option>
<option value="TK"<?php echo preselectOption('TK', $selectedCountryCode); ?>>Tokelau</option>
<option value="TO"<?php echo preselectOption('TO', $selectedCountryCode); ?>>Tonga</option>
<option value="TT"<?php echo preselectOption('TT', $selectedCountryCode); ?>>Trinidad and Tobago</option>
<option value="TN"<?php echo preselectOption('TN', $selectedCountryCode); ?>>Tunisia</option>
<option value="TR"<?php echo preselectOption('TR', $selectedCountryCode); ?>>Turkey</option>
<option value="TM"<?php echo preselectOption('TM', $selectedCountryCode); ?>>Turkmenistan</option>
<option value="TC"<?php echo preselectOption('TC', $selectedCountryCode); ?>>Turks and Caicos Islands</option>
<option value="TV"<?php echo preselectOption('TV', $selectedCountryCode); ?>>Tuvalu</option>
<option value="UG"<?php echo preselectOption('UG', $selectedCountryCode); ?>>Uganda</option>
<option value="UA"<?php echo preselectOption('UA', $selectedCountryCode); ?>>Ukraine</option>
<option value="AE"<?php echo preselectOption('AE', $selectedCountryCode); ?>>United Arab Emirates</option>
<option value="GB"<?php echo preselectOption('GB', $selectedCountryCode); ?>>United Kingdom</option>
<option value="US"<?php echo preselectOption('US', $selectedCountryCode); ?>>United States</option>
<option value="UM"<?php echo preselectOption('UM', $selectedCountryCode); ?>>United States Minor Outlying Islands</option>
<option value="UY"<?php echo preselectOption('UY', $selectedCountryCode); ?>>Uruguay</option>
<option value="UZ"<?php echo preselectOption('UZ', $selectedCountryCode); ?>>Uzbekistan</option>
<option value="VU"<?php echo preselectOption('VU', $selectedCountryCode); ?>>Vanuatu</option>
<option value="VE"<?php echo preselectOption('VE', $selectedCountryCode); ?>>Venezuela, Bolivarian Republic of</option>
<option value="VN"<?php echo preselectOption('VN', $selectedCountryCode); ?>>Viet Nam</option>
<option value="VG"<?php echo preselectOption('VG', $selectedCountryCode); ?>>Virgin Islands, British</option>
<option value="VI"<?php echo preselectOption('VI', $selectedCountryCode); ?>>Virgin Islands, U.S.</option>
<option value="WF"<?php echo preselectOption('WF', $selectedCountryCode); ?>>Wallis and Futuna</option>
<option value="EH"<?php echo preselectOption('EH', $selectedCountryCode); ?>>Western Sahara</option>
<option value="YE"<?php echo preselectOption('YE', $selectedCountryCode); ?>>Yemen</option>
<option value="ZM"<?php echo preselectOption('ZM', $selectedCountryCode); ?>>Zambia</option>
<option value="ZW"<?php echo preselectOption('ZW', $selectedCountryCode); ?>>Zimbabwe</option>