CREATE TABLE `api_access_tokens` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `token` MEDIUMTEXT NULL DEFAULT NULL,
  `client_id` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `revoked_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`));
